Models/PhieuPhat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuPhat
    {
        [DisplayName("Mã phiếu phạt")]
        public int MaPP { get; set; }
        public Nullable<int> MaPM { get; set; }
        [DisplayName("Lý do")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string LyDo { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}

Controllers/PhieuPhatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class PhieuPhatController : Controller
    {
        private ThuVienEntities db = new ThuVienEntities();

        // GET: PhieuPhat
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var phieuPhats = db.PhieuPhats.Include(p => p.PhieuMuon);
            return View(phieuPhats.ToList());
        }

        // GET: PhieuPhat/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhat phieuPhat = db.PhieuPhats.Find(id);
            if (phieuPhat == null)
            {
                return HttpNotFound();
            }
            return View(phieuPhat);
        }

        // GET: PhieuPhat/Create
        public ActionResult Create(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            Session["idPM"] = id;
            return View();
        }

        // POST: PhieuPhat/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LyDo")] PhieuPhat phieuPhat)
        {
            if (ModelState.IsValid)
            {
                phieuPhat.MaPM = int.Parse(Session["idPM"].ToString());
                Session["idPM"] = null;
                db.PhieuPhats.Add(phieuPhat);
                db.SaveChanges();

                
                    List<ChiTietPhieuMuon> cts = db.ChiTietPhieuMuons.Where(x => x.MaPM == phieuPhat.MaPM).ToList();
                    foreach (ChiTietPhieuMuon ct in cts)
                    {
                        Sach sach = db.Saches.Find(ct.MaSach);
                        if (sach != null)
                        {
                            sach.SoLuongTT = sach.SoLuongTT + ct.SoLuong;
                            db.Entry(sach).State = EntityState.Modified;
                            db.SaveChanges();

                        }


                    }

                    
                    

                PhieuMuon phieuMuon = db.PhieuMuons.Where(p => p.MaPM== phieuPhat.MaPM).FirstOrDefault();
                phieuMuon.TrangThai = 1;

                db.Entry(phieuMuon).State = EntityState.Modified;
                db.SaveChanges();
                


                return RedirectToAction("Index","PhieuMuon");
            }

            
            return View(phieuPhat);
        }

        // GET: PhieuPhat/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhat phieuPhat = db.PhieuPhats.Find(id);
            if (phieuPhat == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPM = new SelectList(db.PhieuMuons, "MaPM", "MaNV", phieuPhat.MaPM);
            return View(phieuPhat);
        }

        // POST: PhieuPhat/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPP,MaPM,LyDo")] PhieuPhat phieuPhat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieuPhat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPM = new SelectList(db.PhieuMuons, "MaPM", "MaNV", phieuPhat.MaPM);
            return View(phieuPhat);
        }

        // GET: PhieuPhat/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhieuPhat phieuPhat = db.PhieuPhats.Find(id);
            if (phieuPhat == null)
            {
                return HttpNotFound();
            }
            return View(phieuPhat);
        }

        // POST: PhieuPhat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhieuPhat phieuPhat = db.PhieuPhats.Find(id);
            db.PhieuPhats.Remove(phieuPhat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/PhieuPhat/Create.cshtml
@model QuanLyThuVien.Models.PhieuPhat

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Phiếu phạt</h2>

<div class="card shadow mb-4">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <div class="card-header bg-primary">
                <h4 class="font-weight-bold text-white m-1">Tạo phiếu phạt</h4>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="card-body">
            
                <div class="form-group">
                    @Html.LabelFor(model => model.LyDo, "Lý do", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LyDo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LyDo, "", new { @class = "text-danger" })
                    </div>
                </div>
            
            </div>

            <div class="form-group d-flex align-items-center">
                <div class="col-md-offset-2 col-md-5 text-right">
                    <input type="submit" value="Tạo" class="btn btn-primary pl-3 pr-3" />
                </div>

                <div class="col-md-offset-2 col-md-5 ">
                    @Html.ActionLink("Trở lại", "Index", "PhieuMuon", null , new { @class = "btn btn-default h4 pl-3 pr-3" })
                </div>
            </div>

        </div>
    }

</div>

Views/PhieuPhat/Delete.cshtml
@model QuanLyThuVien.Models.PhieuPhat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Phiếu phạt</h2>

<div class="card shadow mb-4">

    <div class="card-header bg-danger">
        <h3 class="text-white m-1">Xoá phiếu phạt</h3>
    </div>

    <div class="card-body">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LyDo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LyDo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PhieuMuon.MaNV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhieuMuon.MaNV)
            </dd>

        </dl>

        <hr />
        <h3 class="text-danger text-center">Thao tác này sẽ không thể hoàn tác!</h3>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="form-group d-flex align-items-center">
                <div class="col-md-offset-2 col-md-6 text-right">
                    <input type="submit" value="Xóa" class="btn btn-danger pl-3 pr-3" />
                </div>

                <div class="col-md-offset-2 col-md-6 ">
                    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                </div>
            </div>
        }

    </div>

</div>

Views/PhieuPhat/Details.cshtml
@model QuanLyThuVien.Models.PhieuPhat

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Phiếu phạt</h2>

<div class="card shadow mb-4">

    <div>

        <div class="card-header bg-primary">
            <h4 class="font-weight-bold text-white m-1">Chi tiết</h4>
        </div>

        <div class="card-body">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.LyDo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LyDo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhieuMuon.MaNV)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhieuMuon.MaNV)
                </dd>

            </dl>

            <div class="form-group d-flex align-items-center">
                <div class="col-md-offset-2 col-md-5 text-right">
                    <input type="submit" value="Lưu" class="btn btn-primary pl-3 pr-3" />
                </div>

                <div class="col-md-offset-2 col-md-5 ">
                    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                </div>
            </div>

        </div>

    </div>

</div>

Views/PhieuPhat/Edit.cshtml
@model QuanLyThuVien.Models.PhieuPhat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Phiếu phạt</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal card shadow mg-4">

        <div class="card-header bg-primary">
            <h4 class="font-weight-bold text-white m-1">Sửa thông tin</h4>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaPP)

    <div class="card-body">

        <div class="form-group">
            @Html.LabelFor(model => model.MaPP, "Mã phiếu phạt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaPP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaPP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LyDo, "Lý do", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LyDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LyDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group d-flex align-items-center">
            <div class="col-md-offset-2 col-md-5 text-right">
                <input type="submit" value="Lưu" class="btn btn-primary pl-3 pr-3" />
            </div>

            <div class="col-md-offset-2 col-md-5 ">
                @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
            </div>
        </div>

    </div>
    </div>
}

Views/PhieuPhat/Index.cshtml
@model IEnumerable<QuanLyThuVien.Models.PhieuPhat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<div class="card shadow mb-4">

    <div class=" form-row card-header py-3 m-0">
        <h4 class="m-0 font-weight-bold text-primary form-group col-sm-6">Danh sách phiếu phạt</h4>
        <div class="form-group col-sm-6 text-right justify-content-center">
            <i class="fa fa-plus text-primary"></i>
            @Html.ActionLink("Tạo phiếu phạt", "Create", "PhieuPhat", null, new { @class = "m-0 font-weight-bold text-primary  text-decoration-none h5" })
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>Lý do</th>
                            <th>Mã nhân viên</th>
                            <th>Trạng thái</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Lý do</th>
                            <th>Mã nhân viên</th>
                            <th>Trạng thái</th>
                            <th>Chức năng</th>
                        </tr>
                    </tfoot>
                    <tbody>


                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LyDo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhieuMuon.MaNV)
                                </td>
                                @if (item.PhieuMuon.TrangThai == 0)
                                {
                                    <td class="text-primary">
                                        @Html.DisplayFor(modelItem => item.PhieuMuon.TrangThai1.name)
                                    </td>
                                }
                                else if (item.PhieuMuon.TrangThai == 1)
                                {
                                    <td class="text-success">
                                        @Html.DisplayFor(modelItem => item.PhieuMuon.TrangThai1.name)
                                    </td>
                                }
                                else
                                {
                                    <td class="text-danger">
                                        @Html.DisplayFor(modelItem => item.PhieuMuon.TrangThai1.name)
                                    </td>
                                }
                            <td>
                                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.MaPP }) |
                                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaPP }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.MaPP })
                            </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

     </div>