Models/DocGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DocGia
    {
        [DisplayName("Mã độc giả")]
        public int MaDG { get; set; }
        [DisplayName("Nghề nghiệp")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string NgheNghiep { get; set; }
        public int LoaiDG { get; set; }
        public Nullable<int> MaNguoi { get; set; }
      
        public virtual LoaiDG LoaiDG1 { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
        public virtual Nguoi Nguoi { get; set; }
    }
}

Controllers/DocGiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class DocGiaController : Controller
    {
        private ThuVienEntities db = new ThuVienEntities();

        // GET: DocGia
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var docGias = db.DocGias.Include(d => d.LoaiDG1).Include(d => d.TheThuVien).Include(d => d.Nguoi);
            return View(docGias.ToList());
        }

        // GET: DocGia/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGias.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            return View(docGia);
        }

        // GET: DocGia/Create
        public ActionResult Create()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.LoaiDG = new SelectList(db.LoaiDGs, "id", "name");
            return View();
        }

        // POST: DocGia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NgheNghiep,LoaiDG,Nguoi")] DocGia docGia)
        {
            
            if (ModelState.IsValid && docGia.Nguoi != null)
            {
                db.Nguois.Add(docGia.Nguoi);
                db.SaveChanges();
                Nguoi nguoi = db.Nguois.ToList().Last();
                docGia.MaNguoi = nguoi.MaNguoi;

                TheThuVien theThuVien = new TheThuVien();
                
                

                db.DocGias.Add(docGia);
                db.SaveChanges();
                DocGia newdocGia = db.DocGias.ToList().Last();
                
                DateTime dateTime = DateTime.Now.Date;
                if (newdocGia.LoaiDG == 0)
                {
                    dateTime = dateTime.AddDays(60);
                } else if (newdocGia.LoaiDG == 1) 
                {
                    dateTime = dateTime.AddDays(180);
                } else if (newdocGia.LoaiDG == 2)
                {
                    dateTime = dateTime.AddDays(365);
                }

                theThuVien.MaDG = newdocGia.MaDG;
                theThuVien.ThoiHan = dateTime;

                db.TheThuViens.Add(theThuVien);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.LoaiDG = new SelectList(db.LoaiDGs, "id", "name", docGia.LoaiDG);
            ViewBag.MaDG = new SelectList(db.TheThuViens, "MaDG", "MaDG", docGia.MaDG);
            ViewBag.MaNguoi = new SelectList(db.Nguois, "MaNguoi", "HoTen", docGia.MaNguoi);
            return View(docGia);
        }

        // GET: DocGia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGias.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoaiDG = new SelectList(db.LoaiDGs, "id", "name", docGia.LoaiDG);
            ViewBag.MaDG = new SelectList(db.TheThuViens, "MaDG", "MaDG", docGia.MaDG);
            ViewBag.MaNguoi = new SelectList(db.Nguois, "MaNguoi", "HoTen", docGia.MaNguoi);
            return View(docGia);
        }

        // POST: DocGia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDG,NgheNghiep,LoaiDG,MaNguoi")] DocGia docGia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(docGia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiDG = new SelectList(db.LoaiDGs, "id", "name", docGia.LoaiDG);
            ViewBag.MaDG = new SelectList(db.TheThuViens, "MaDG", "MaDG", docGia.MaDG);
            ViewBag.MaNguoi = new SelectList(db.Nguois, "MaNguoi", "HoTen", docGia.MaNguoi);
            return View(docGia);
        }

        // GET: DocGia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGias.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            return View(docGia);
        }

        // POST: DocGia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DocGia docGia = db.DocGias.Find(id);

            List<PhieuMuon> phieuMuons = db.PhieuMuons.Where(x => x.MaDG == docGia.MaDG).ToList();
            foreach (PhieuMuon phieuMuon in phieuMuons)
            {
                List<ChiTietPhieuMuon> cts = db.ChiTietPhieuMuons.Where(x => x.MaPM == phieuMuon.MaPM).ToList();
                foreach (ChiTietPhieuMuon ct in cts)
                {
                    db.ChiTietPhieuMuons.Remove(ct);
                    db.SaveChanges();
                }

                List<PhieuPhat> pp = db.PhieuPhats.Where(x => x.MaPM == phieuMuon.MaPM).ToList();
                foreach (PhieuPhat ct in pp)
                {
                    db.PhieuPhats.Remove(ct);
                    db.SaveChanges();
                }

                db.PhieuMuons.Remove(phieuMuon);
                db.SaveChanges();

            }


            TheThuVien theThuVien = db.TheThuViens.Find(id);
            db.TheThuViens.Remove(theThuVien);
            
            db.SaveChanges();
            Nguoi nguoi = db.Nguois.Where(x => x.MaNguoi == docGia.MaNguoi).FirstOrDefault();
            db.DocGias.Remove(docGia);
            db.SaveChanges();

            
            if (nguoi != null)
            {
                db.Nguois.Remove(nguoi);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/DocGia/Create.cshtml
@model QuanLyThuVien.Models.DocGia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Quản lý độc giả</h2>


<div class="card shadow mb-4 ">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="card-header bg-primary">
                <h4 class="font-weight-bold text-white mt-1">Thêm độc giả</h4>
            </div>


            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                
                <!--Start form-->
                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.HoTen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.Gioitinh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.Gioitinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.Gioitinh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.NgaySinh, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.NgaySinh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LoaiDG, "Loại độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LoaiDG", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiDG, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgheNghiep, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NgheNghiep, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NgheNghiep, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.Sdt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.Sdt, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!--End Form-->
                <div class="form-group d-flex align-items-center">
                    <div class="col-md-offset-2 col-md-5 text-right">
                        <input type="submit" value="Thêm" class="btn btn-primary pl-3 pr-3" />
                    </div>

                    <div class="col-md-offset-2 col-md-5 ">
                        @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                    </div>
                </div>


            </div>





        </div>
    }



</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/DocGia/Delete.cshtml
@model QuanLyThuVien.Models.DocGia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý độc giả</h2>

<div class="card shadow mb-4">

    <div>
        <div class="card-header bg-danger">
            <h3 class="text-white m-1">Xoá độc giả</h3>
        </div>

        <div class="card-body">

            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Nguoi.HoTen)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nguoi.HoTen)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TheThuVien.MaDG)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TheThuVien.MaDG)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LoaiDG1.name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LoaiDG1.name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Nguoi.DiaChi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nguoi.DiaChi)
                </dd>

            </dl>

            <hr />
            <h3 class="text-danger text-center">Thao tác này sẽ không thể hoàn tác!</h3>
            <hr />

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


                <div class="form-group d-flex align-items-center">
                    <div class="col-md-offset-2 col-md-6 text-right">
                        <input type="submit" value="Xóa" class="btn btn-danger pl-3 pr-3" />
                    </div>

                    <div class="col-md-offset-2 col-md-6 ">
                        @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                    </div>
                </div>
            }

        </div>

    </div>

Views/DocGia/Details.cshtml
@model QuanLyThuVien.Models.DocGia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DocGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgheNghiep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgheNghiep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDG1.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDG1.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TheThuVien.MaDG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TheThuVien.MaDG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nguoi.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nguoi.HoTen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaDG }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/DocGia/Edit.cshtml
@model QuanLyThuVien.Models.DocGia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý độc giả</h2>

<div class="card shadow mb-4">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="card-header bg-primary">
                <h4 class="font-weight-bold m-1 text-white">Sửa thông tin</h4>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaDG)

            <div class="card-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.HoTen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.Gioitinh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.Gioitinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.Gioitinh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.NgaySinh, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.NgaySinh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LoaiDG, "Loại độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LoaiDG", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiDG, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgheNghiep, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NgheNghiep, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NgheNghiep, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nguoi.Sdt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nguoi.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nguoi.Sdt, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group d-flex align-items-center">
                    <div class="col-md-offset-2 col-md-5 text-right">
                        <input type="submit" value="lưu" class="btn btn-primary mt-1 pl-3 pr-3" />
                    </div>

                    <div class="col-md-offset-2 col-md-5 ">
                        @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                    </div>
                </div>

            </div>
        </div>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/DocGia/Index.cshtml
@model IEnumerable<QuanLyThuVien.Models.DocGia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý độc giả</h2>

<div class="card shadow mb-4 ">

    <div class=" form-row card-header m-0">
        <h4 class="font-weight-bold text-primary col-sm-6 mt-1">Danh sách độc giả</h4>
        <div class=" col-sm-6 text-right justify-content-center mt-2">
            <i class="fa fa-plus text-primary"></i>
            @Html.ActionLink("Thêm độc giả", "Create", "DocGia", null, new { @class = "font-weight-bold text-primary  text-decoration-none h5" })
        </div>

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã độc giả</th>
                        <th>Loại độc giả</th>
                        <th>Tên độc giả</th>
                        <th>Ngày sinh</th>
                        <th>Giới tính</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Thời hạn</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Mã độc giả</th>
                        <th>Loại độc giả</th>
                        <th>Tên độc giả</th>
                        <th>Ngày sinh</th>
                        <th>Giới tính</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Thời hạn</th>
                        <th>Chức năng</th>
                    </tr>
                </tfoot>
                <tbody>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaDG)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LoaiDG1.name)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoi.HoTen)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoi.NgaySinh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoi.Gioitinh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoi.DiaChi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoi.Sdt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TheThuVien.ThoiHan)
                            </td>
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.MaDG }) |

                                @Html.ActionLink("Xóa", "Delete", new { id = item.MaDG })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts {
    <!-- Page level plugins -->
    @Scripts.Render("~/vendor/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/vendor/datatables/dataTables.bootstrap4.min.js")

    <!-- Page level custom scripts -->
    @Scripts.Render("~/js/demo/datatables-demo.js")
}