Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập tài khoản")]
        [MinLength(6,ErrorMessage ="Tài khoản tối thiểu 6 kí tự")]
        public string TaiKhoan1 { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [MinLength(6, ErrorMessage = "Mật khẩu tối thiểu 6 kí tự")]
        
        public string MatKhau { get; set; }
        [DisplayName("Loại tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public Nullable<int> LoaiTK { get; set; }
        [DisplayName("Mã nhân viên")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string MaNV { get; set; }
    
        public virtual LoaiTK LoaiTK1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public string LoginErrorMessage { get; internal set; }
        public string ErMes { get; internal set; }
    }
}

Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class TaiKhoanController : Controller
    {
        private ThuVienEntities db = new ThuVienEntities();

        // GET: TaiKhoan
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var taiKhoans = db.TaiKhoans.Include(t => t.LoaiTK1).Include(t => t.NhanVien);
            return View(taiKhoans.ToList());
        }

        // GET: TaiKhoan/Details/5
        public ActionResult Details(string id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoan/Create
        public ActionResult Create()
        {
            
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name");
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu");
            return View();
        }

        // POST: TaiKhoan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaiKhoan1,MatKhau,LoaiTK,MaNV")] TaiKhoan taiKhoan)
        {
            if (db.TaiKhoans.Find(taiKhoan.TaiKhoan1) != null)
            {
                taiKhoan.ErMes = "Tài khoản không hợp lệ";
                ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name", taiKhoan.LoaiTK);
                ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu", taiKhoan.MaNV);
                return View(taiKhoan);
            }

            if (db.NhanViens.Find(taiKhoan.MaNV) == null)
            {
                taiKhoan.ErMes = "Mã nhân viên không hợp lệ";
                ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name", taiKhoan.LoaiTK);
                ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu", taiKhoan.MaNV);
                return View(taiKhoan);
            }
            if (ModelState.IsValid)
            {
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name", taiKhoan.LoaiTK);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu", taiKhoan.MaNV);
            return View(taiKhoan);
        }

        // GET: TaiKhoan/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name", taiKhoan.LoaiTK);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu", taiKhoan.MaNV);
            return View(taiKhoan);
        }

        // POST: TaiKhoan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaiKhoan1,MatKhau,LoaiTK,MaNV")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiTK = new SelectList(db.LoaiTKs, "id", "name", taiKhoan.LoaiTK);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "Chucvu", taiKhoan.MaNV);
            return View(taiKhoan);
        }

        // GET: TaiKhoan/Delete/5
        public ActionResult Delete(string id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TaiKhoan/Create.cshtml
@model QuanLyThuVien.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý tài khoản</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">

        <div class="form-horizontal">

            <div class="card-header bg-primary">
                <h4 class="font-weight-bold text-white m-1">Tạo tài khoản mới</h4>
            </div>

            <div class="card-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="text-danger">@Html.DisplayFor(model => model.ErMes)</div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TaiKhoan1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaiKhoan1, new { htmlAttributes = new { @class = "form-control" } })

                        @Html.ValidationMessageFor(model => model.TaiKhoan1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaNV, "Mã nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LoaiTK, "Loại tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LoaiTK", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiTK, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group d-flex align-items-center">
                    <div class="col-md-offset-2 col-md-5 text-right">
                        <input type="submit" value="Thêm" class="btn btn-primary pl-3 pr-3" />
                    </div>

                    <div class="col-md-offset-2 col-md-5 ">
                        @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                    </div>
                </div>

            </div>

        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/TaiKhoan/Delete.cshtml
@model QuanLyThuVien.Models.TaiKhoan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý tài khoản</h2>

<div class="card shadow mb-4">

    <div class="card-header bg-danger">
        <h3 class="text-white m-1">Xoá tài khoản</h3>
    </div>

    <div class="card-body h5">

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.TaiKhoan1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TaiKhoan1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MatKhau)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LoaiTK1.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LoaiTK1.name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NhanVien.Chucvu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhanVien.Chucvu)
            </dd>

        </dl>

        <hr />
        <h3 class="text-danger text-center">Thao tác này sẽ không thể hoàn tác!</h3>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="form-group d-flex align-items-center">
                <div class="col-md-offset-2 col-md-6 text-right">
                    <input type="submit" value="Xóa" class="btn btn-danger pl-3 pr-3" />
                </div>

                <div class="col-md-offset-2 col-md-6 ">
                    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                </div>
            </div>
        }

    </div>

</div>

Views/TaiKhoan/Details.cshtml
@model QuanLyThuVien.Models.TaiKhoan

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiTK1.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTK1.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.Chucvu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.Chucvu)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaiKhoan1 }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/TaiKhoan/Edit.cshtml
@model QuanLyThuVien.Models.TaiKhoan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý tài khoản</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">

        <div class="form-horizontal">
            <div class="card-header bg-primary">
                <h4 class="font-weight-bold text-white m-1 d-inline">Sửa thông tin tài khoản </h4>
            </div>

            <div class="card-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.TaiKhoan1)

                <div class="form-group">
                    @Html.LabelFor(model => model.TaiKhoan1, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaiKhoan1, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                        @Html.ValidationMessageFor(model => model.TaiKhoan1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LoaiTK, "Loại tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LoaiTK", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LoaiTK, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaNV, "Mã nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group d-flex align-items-center mt-4">
                    <div class="col-md-offset-2 col-md-5 text-right">
                        <input type="submit" value="Lưu" class="btn btn-primary pl-3 pr-3" />
                    </div>

                    <div class="col-md-offset-2 col-md-5 ">
                        @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-default h4 pl-3 pr-3" })
                    </div>
                </div>

            </div>

        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/TaiKhoan/Index.cshtml
@model IEnumerable<QuanLyThuVien.Models.TaiKhoan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý tài khoản</h2>

<div class="card shadow mb-4">

    <div class=" form-row card-header m-0">
        <h4 class="font-weight-bold text-primary col-sm-6 mt-1">Danh sách tài khoản</h4>
        <div class=" col-sm-6 text-right justify-content-center mt-2">
            <i class="fa fa-plus text-primary"></i>
            @Html.ActionLink("Tạo tài khoản", "Create", "TaiKhoan", null, new { @class = "font-weight-bold text-primary  text-decoration-none h5" })
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="text-center">
                    <tr>
                        <th>Username</th>
                        <th>Mật khẩu</th>
                        <th>Mã nhân viên</th>
                        <th>Loại tài khoản</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tfoot class="text-center">
                    <tr>
                        <th>Username</th>
                        <th>Mật khẩu</th>
                        <th>Mã nhân viên</th>
                        <th>Loại tài khoản</th>
                        <th>Chức năng</th>
                    </tr>
                </tfoot>
                <tbody>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TaiKhoan1)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MatKhau)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaNV)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LoaiTK1.name)
                            </td>
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.TaiKhoan1 }) |


                                @Html.ActionLink("Xóa", "Delete", new { id = item.TaiKhoan1 })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>

</div>

@section Scripts {
    <!-- Page level plugins -->
    @Scripts.Render("~/vendor/datatables/jquery.dataTables.min.js")
    @Scripts.Render("~/vendor/datatables/dataTables.bootstrap4.min.js")

    <!-- Page level custom scripts -->
    @Scripts.Render("~/js/demo/datatables-demo.js")
}